
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmacica-demo-mz
spec:
  selector:
    matchLabels:
      app: cmacica-demo-mz
  replicas: 1
  template:
    metadata:
      labels:
        app: cmacica-demo-mz
        env: dev
    spec:
      containers:
        - name: cmacica-demo-mz
          image: mzegarra/hello-node:v1
          ports:
            - containerPort: 8888
