apiVersion: v1
kind: Service
metadata:
  name: cmacica-demo-mz
  labels:
    app: cmacica-demo-mz
spec:
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8888
  selector:
    app: cmacica-demo-mz
  #type: ClusterIP
  type: LoadBalancer
