apiVersion: v1
kind: Service
metadata:
  name: cmacica-mongo-express-mz
  labels:
    app: cmacica-mongo-express-mz
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: cmacica-mongo-express-mz
  type: LoadBalancer
